import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import ts from 'typescript';
await mkdir('.sites-runtime/tests',{recursive:true});
for(const name of ['planner','planner-actions','validation']){
 const source=await readFile(`lib/${name}.ts`,'utf8');
 const {outputText}=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}});
 await writeFile(`.sites-runtime/tests/${name}.mjs`,outputText.replaceAll("from './planner'","from './planner.mjs'"));
}
const {samplePlanner,sortedEntries,addDays,dateKey}=await import('../.sites-runtime/tests/planner.mjs');
const {moveEntry,reorderEntries,normalizeNewOrders,rangeDates}=await import('../.sites-runtime/tests/planner-actions.mjs');
const {plannerSchema,validDate}=await import('../.sites-runtime/tests/validation.mjs');
const date='2026-09-15',sample=samplePlanner(date);
assert(plannerSchema.safeParse(sample).success);
assert.equal(addDays('2026-12-31',1),'2027-01-01');
assert.equal(addDays('2028-02-28',1),'2028-02-29');
assert.equal(dateKey(new Date('2026-09-15T17:00:00Z')),'2026-09-16');
assert.equal(validDate('2026-02-29'),false);
assert.equal(validDate('2028-02-29'),true);
assert.throws(()=>rangeDates('2026-02-10','2026-02-01'));
assert.throws(()=>rangeDates('2026-01-01','2027-01-02'));
const oldNext=sortedEntries(sample,'2026-09-16');
const ids=sortedEntries(sample,date).map(e=>e.id).reverse();
const reordered=reorderEntries(sample,date,ids);
assert.deepEqual(sortedEntries(reordered,date).map(e=>e.id),ids);
assert.deepEqual(sortedEntries(reordered,'2026-09-16'),oldNext);
assert.throws(()=>reorderEntries(sample,date,['e1','e1']));
const moved=moveEntry(sample,'e2','2026-09-16');
assert.equal(sortedEntries(moved,date).length,4);
assert.equal(sortedEntries(moved,'2026-09-16').at(-1).id,'e2');
assert.throws(()=>moveEntry(sample,'e1','2026-09-16'));
const extended=moveEntry(sample,'e2','2026-11-10');
assert.equal(extended.projects.find(p=>p.id==='p2').end,'2026-11-10');
assert.equal(normalizeNewOrders(sample,[{...sample.entries[1],date:'2026-09-16'}])[0].order,1);
const completed={...sample,entries:sample.entries.map(e=>e.id==='e1'?{...e,done:true}:e)};
assert.equal(completed.entries.filter(e=>e.taskId==='t1'&&!e.done).length,2);
assert.equal(completed.entries.find(e=>e.id==='e9').date,'2026-09-14');
const bad=structuredClone(sample);bad.entries[0].taskId='missing';assert(!plannerSchema.safeParse(bad).success);
console.log('PASS: date boundaries, timezone, cross-project ordering, independent daily completion, rescheduling, project expansion, invalid references');
if(process.argv.includes('--api')){
 const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8787';
 assert(/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base),'API tests must use a local server');
 const prefix=`dayweave-test-${Date.now()}`;
 const request=async(user,method='GET',body,extra={})=>fetch(base+'/api/planner',{method,headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{}),'Content-Type':'application/json',Origin:base,...extra},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await request(null)).status,401);
 let response=await request(prefix);assert.equal(response.status,200);assert.equal((await response.json()).revision,0);
 response=await request(prefix,'PUT',{revision:0,state:sample});assert.equal(response.status,200);assert.equal((await response.json()).revision,1);
 response=await request(prefix);let saved=await response.json();assert.deepEqual(saved.state,sample);
 const independent=await (await request(prefix+'-other')).json();assert.equal(independent.state.projects.length,0);
 assert.equal((await request(prefix,'PUT',{revision:0,state:reordered})).status,409);
 response=await request(prefix,'PUT',{revision:1,state:reordered});assert.equal(response.status,200);
 saved=await (await request(prefix)).json();assert.deepEqual(sortedEntries(saved.state,date).map(e=>e.id),ids);
 const race=await Promise.all([request(prefix,'PUT',{revision:2,state:moved}),request(prefix,'PUT',{revision:2,state:completed})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);
 assert.equal((await request(prefix,'PUT',{revision:3,state:bad})).status,400);
 assert.equal((await request(prefix,'PUT',{revision:3,state:sample},{Origin:'https://unrelated.example'})).status,403);
 const remaining=await (await request(prefix)).json();assert.equal(remaining.revision,3);
 assert.equal((await request(prefix,'PUT',{revision:3,state:{projects:[],tasks:[],entries:[]}})).status,200);
 assert.equal((await (await request(prefix)).json()).state.entries.length,0);
 console.log('PASS: built Worker auth, durable reload, user isolation, stale revisions, concurrent writes, validation, cross-origin rejection, deletion');
}
