'use client';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { CalendarDays, Layers3, ListTodo, Plus, ChevronLeft, ChevronRight, ArrowUpRight, GripVertical, Clock3, CircleHelp, Cloud, CloudOff, Check, Sparkles, ArrowUp, ArrowDown, Pencil, Trash2, X, RotateCw, LogIn, LoaderCircle } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarProvider, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetTitle, SheetDescription, SheetHeader } from '@/components/ui/sheet';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { addDays, dateKey, dayLabel, monday, sortedEntries, minutesLabel, type Project, type Task, type Entry } from '@/lib/planner';
import { moveEntry, reorderEntries } from '@/lib/planner-actions';
import { validDate } from '@/lib/validation';
import { usePlanner } from './use-planner';
import { ProjectEditor, TaskEditor } from './planner-editors';

type Editor = {kind:'project';project?:Project}|{kind:'task';task?:Task;entry?:Entry;projectId?:string}|{kind:'move';entry:Entry};
export default function PlannerApp(){
 const [today,setToday]=useState(()=>dateKey()),[selected,setSelected]=useState(today),[start,setStart]=useState(monday(today)),[range,setRange]=useState('14'),[view,setView]=useState<'timeline'|'backlog'>('timeline');
 const [editor,setEditor]=useState<Editor|null>(null),[projectId,setProjectId]=useState<string|null>(null),[remove,setRemove]=useState<{kind:'task'|'project';id:string;name:string}|null>(null),[dragId,setDragId]=useState<string|null>(null),[moveDate,setMoveDate]=useState(today);
 const planner=usePlanner(today),{data,demo,ready,busy,online,authenticated,error,commit}=planner;
 const taskMap=new Map(data.tasks.map(t=>[t.id,t])),projectMap=new Map(data.projects.map(p=>[p.id,p]));
 const daily=sortedEntries(data,selected),backlog=data.entries.filter(e=>!e.done&&e.date<today).sort((a,b)=>a.date.localeCompare(b.date)||a.order-b.order),entries=view==='backlog'?backlog:daily;
 const total=daily.reduce((n,e)=>n+(e.minutes||0),0),unknown=daily.filter(e=>e.minutes===null).length,done=daily.filter(e=>e.done).length,dayProjectIds=new Set(daily.map(e=>taskMap.get(e.taskId)?.projectId));
 const visibleProject=projectId?projectMap.get(projectId):null;
 const monthDays=new Date(Number(start.slice(0,4)),Number(start.slice(5,7)),0).getDate();
 const days=Array.from({length:range==='month'?monthDays:Number(range)},(_,i)=>addDays(start,i));
 const canEdit=ready&&!busy;
 planner.pause.current=!!editor||!!remove;
 useEffect(()=>{const timer=setInterval(()=>{const next=dateKey();if(next!==today){setToday(next);setSelected(d=>d===today?next:d);}},60000);return()=>clearInterval(timer)},[today]);
 function chooseDay(date:string){if(!validDate(date))return;setSelected(date);setView('timeline');if(date<start||date>days.at(-1)!)setStart(range==='month'?date.slice(0,8)+'01':monday(date));}
 function setPeriod(value:string){setRange(value);setStart(value==='month'?selected.slice(0,8)+'01':monday(selected));}
 function navigate(direction:number){if(range==='month'){const d=new Date(start+'T12:00:00');d.setMonth(d.getMonth()+direction);setStart(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`);}else setStart(addDays(start,Number(range)*direction));}
 function newProject(){if(!authenticated){toast.info('请先登录，再创建自己的项目');return;}if(demo)planner.startOwn();setEditor({kind:'project'});}
 function newTask(id?:string){if(!data.projects.length){toast.info('先创建一个项目，再安排任务');newProject();return;}setEditor({kind:'task',projectId:id});}
 function editEntry(entry:Entry){const task=taskMap.get(entry.taskId);if(task)setEditor({kind:'task',task,entry});}
 function schedule(entry:Entry){setMoveDate(today);setEditor({kind:'move',entry});}
 async function toggle(entry:Entry,done:boolean){return commit(s=>({...s,entries:s.entries.map(e=>e.id===entry.id?{...e,done}:e)}),done?'当天工作已完成':'已恢复为未完成');}
 async function reorder(id:string,targetId:string){if(id===targetId||view==='backlog')return;const ids=daily.map(e=>e.id),from=ids.indexOf(id),to=ids.indexOf(targetId);if(from<0||to<0)return;ids.splice(from,1);ids.splice(to,0,id);await commit(s=>reorderEntries(s,selected,ids),'当天顺序已保存');}
 async function deleteConfirmed(){if(!remove)return;const ok=await commit(s=>{const ids=remove.kind==='task'?new Set([remove.id]):new Set(s.tasks.filter(t=>t.projectId===remove.id).map(t=>t.id));return {projects:remove.kind==='project'?s.projects.filter(p=>p.id!==remove.id):s.projects,tasks:s.tasks.filter(t=>!ids.has(t.id)),entries:s.entries.filter(e=>!ids.has(e.taskId))};},remove.kind==='task'?'任务已删除':'项目已删除');if(ok){if(remove.kind==='project')setProjectId(null);setRemove(null);}}
 // WebMCP navigates and reads exactly the workspace currently shown by the UI.
 const actions=useRef({data,chooseDay,selected,ready,demo});actions.current={data,chooseDay,selected,ready,demo};
 useEffect(()=>{
 type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
 const context=(document as unknown as {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;const lifecycle=new AbortController();
 const tools:Tool[]=[{name:'get_day_plan',title:'读取某天安排',description:'读取当前个人工作空间在指定日期的任务、项目、备注、完成状态和顺序。示例模式会在结果中明确标记。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){const date=(input as {date?:string})?.date;if(typeof date!=='string'||!validDate(date))throw new Error('日期必须为有效的 YYYY-MM-DD');const a=actions.current;if(!a.ready)throw new Error('安排尚未加载');return {date,demo:a.demo,entries:sortedEntries(a.data,date).map(e=>{const t=a.data.tasks.find(t=>t.id===e.taskId),p=a.data.projects.find(p=>p.id===t?.projectId);return {...e,task:t?.title,project:p?.name,taskNote:t?.note}})};}},
 {name:'show_plan_date',title:'查看指定日期',description:'选择日期并打开当日任务清单，不修改已保存的任务。',inputSchema:{type:'object',properties:{date:{type:'string'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const date=(input as {date?:string})?.date;if(typeof date!=='string'||!validDate(date))throw new Error('日期必须为有效的 YYYY-MM-DD');actions.current.chooseDay(date);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {selectedDate:date};}}];
 for(const t of tools){try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 return()=>lifecycle.abort();
 },[]);
 return <SidebarProvider style={{'--sidebar-width':'220px'} as CSSProperties}><Toaster position="bottom-right" richColors/>
 <Sidebar className="app-sidebar"><SidebarHeader><button className="brand" aria-label="日序首页" onClick={()=>chooseDay(today)}><span className="brand-mark"><Layers3 size={22}/></span><strong>日序<span>DAYWEAVE</span></strong></button></SidebarHeader><SidebarContent><p className="nav-caption">我的工作空间</p><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={view==='timeline'} onClick={()=>setView('timeline')}><CalendarDays/><span>项目时间轴</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={view==='backlog'} onClick={()=>setView('backlog')}><ListTodo/><span>未完成待处理</span>{backlog.length>0&&<span className="count-pill">{backlog.length}</span>}</SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="sidebar-projects"><p className="nav-caption">我的项目 <button aria-label="添加项目" disabled={!canEdit} onClick={newProject}><Plus size={15}/></button></p>{data.projects.map(p=><button key={p.id} className="project-nav" onClick={()=>setProjectId(p.id)}><i style={{background:p.color}}/><span>{p.name}</span></button>)}{!data.projects.length&&<p className="sidebar-empty">从第一个项目开始</p>}</div></SidebarContent><SidebarFooter><div className="side-tip"><span>把项目放在一起，<br/>把每一天安排清楚。</span><div className="mini-lines"><i/><i/><i/></div></div><div className="profile"><span className="avatar">我</span><div><b title={planner.name}>个人工作空间</b><small><Cloud size={12}/>{demo?'示例模式':authenticated?'电脑与手机同步':'登录后同步'}</small></div></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger" aria-label="打开工作空间菜单"/>工作空间 <span>/</span><b>{view==='timeline'?'项目时间轴':'未完成待处理'}</b></div><div className="top-actions">{authenticated?<button className={`sync-status ${error?'sync-error':''}`} disabled={busy} title="刷新云端安排" onClick={()=>void planner.refresh(!ready)}>{busy?<LoaderCircle className="spinning" size={15}/>:online?<Cloud size={15}/>:<CloudOff size={15}/>}<span role="status">{busy?'正在保存':!ready?'正在读取':demo?'示例模式':online?'已同步':'暂时离线'}</span></button>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="btn compact"><LogIn size={14}/> 登录并同步</a>}</div></header>
 <div className="page-content">{error&&<div className="error-banner" role="alert"><CloudOff size={17}/><span>{error}</span><button disabled={busy} onClick={()=>void planner.refresh(!ready)}><RotateCw size={14}/> 重试</button></div>}
 <div className="page-heading"><div><p className="eyebrow">PLAN YOUR DAYS</p><h1>{view==='timeline'?'项目时间轴':'未完成待处理'}<span className="title-dot"/></h1><p className="subtitle">{view==='timeline'?'看见项目全局，安排好每一个今天。':'之前的计划仍在这里，按自己的节奏重新安排。'}</p></div><button className="btn primary" disabled={!canEdit} onClick={newProject}><Plus size={17}/> 新建项目</button></div>
 {demo&&ready&&<div className="demo-banner"><span><Sparkles size={15}/> 你正在体验示例，修改不会保存到自己的安排。</span>{authenticated?<button onClick={newProject}>创建我的第一个项目 <ArrowUpRight size={14}/></button>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top">登录，开始我的安排 <ArrowUpRight size={14}/></a>}</div>}
 {view==='timeline'&&<><div className="overview-strip"><div><span className="stat-icon purple"><Layers3 size={19}/></span><div><span>进行中的项目</span><strong>{data.projects.filter(p=>p.start<=today&&p.end>=today).length}<small>个项目</small></strong></div></div><div><span className="stat-icon blue"><ListTodo size={19}/></span><div><span>{selected===today?'今日安排':'所选日安排'}</span><strong>{daily.length}<small>项任务</small></strong></div></div><div><span className="stat-icon amber"><Clock3 size={19}/></span><div><span>预计投入</span><strong>{Number((total/60).toFixed(1))}<small>小时{unknown>0?` · ${unknown} 项未估时`:''}</small></strong></div></div><div className="overview-progress"><span>{selected===today?'今日已完成':'当日已完成'} <b>{done} / {daily.length}</b></span><Progress aria-label="当日任务完成进度" value={daily.length?done/daily.length*100:0}/></div></div>
 <section className="timeline-section" aria-label="项目时间轴"><div className="section-toolbar"><div className="date-navigation"><h2>{new Date(start+'T12:00').getFullYear()} 年 {new Date(start+'T12:00').getMonth()+1} 月</h2><div className="arrow-group"><button aria-label="上一时间段" onClick={()=>navigate(-1)}><ChevronLeft size={17}/></button><button aria-label="下一时间段" onClick={()=>navigate(1)}><ChevronRight size={17}/></button></div><button className="btn compact" onClick={()=>{chooseDay(today);setStart(range==='month'?today.slice(0,8)+'01':monday(today))}}>今天</button></div><Tabs value={range} onValueChange={setPeriod}><TabsList aria-label="时间轴范围"><TabsTrigger value="7">周</TabsTrigger><TabsTrigger value="14">双周</TabsTrigger><TabsTrigger value="month">月</TabsTrigger></TabsList></Tabs></div>
 <div className="timeline-scroll"><div className="timeline" style={{'--days':days.length,minWidth:days.length>14?`${180+days.length*43}px`:undefined} as CSSProperties}><div className="timeline-header"><div className="timeline-label">项目 / 时间跨度</div>{days.map(d=><button key={d} className={`day-head ${d===selected?'selected':''} ${[0,6].includes(new Date(d+'T12:00').getDay())?'weekend':''}`} onClick={()=>chooseDay(d)} aria-label={`查看 ${d}`} aria-pressed={d===selected}><small>{['日','一','二','三','四','五','六'][new Date(d+'T12:00').getDay()]}</small><b>{Number(d.slice(-2))}</b>{d===today&&<i/>}</button>)}</div>
 {data.projects.map(p=><div key={p.id} className="timeline-row"><button className="timeline-label project-label" onClick={()=>setProjectId(p.id)} title={p.name}><div><i style={{background:p.color}}/><strong>{p.name}</strong></div><small>{dayLabel(p.start)} — {dayLabel(p.end)}</small></button>{days.map(d=>{const items=data.entries.filter(e=>e.date===d&&taskMap.get(e.taskId)?.projectId===p.id);return <button key={d} className={`timeline-cell ${d===selected?'selected':''} ${d>=p.start&&d<=p.end?'in-project':''}`} style={{'--project-color':p.color} as CSSProperties} onClick={()=>chooseDay(d)} aria-label={`${p.name} ${d} ${items.length}项任务`}>{d>=p.start&&d<=p.end&&<span className={`project-band ${d===p.start||d===days[0]?'band-start':''} ${d===p.end||d===days.at(-1)?'band-end':''}`}>{items.length>0&&<b className={items.every(e=>e.done)?'all-done':''}>{items.every(e=>e.done)?<Check size={12}/>:items.length}</b>}</span>}</button>})}</div>)}
 {!data.projects.length&&<div className="empty-projects"><Layers3 size={30}/><h3>为你的第一个项目留出时间</h3><p>设置项目周期，再把工作安排到每天。</p><button className="btn primary" disabled={!canEdit} onClick={newProject}><Plus size={16}/> 创建项目</button></div>}
 </div></div><div className="timeline-footer"><span><i className="legend-line"/> 项目周期 <i className="legend-count">2</i> 当日任务数</span><span>点击日期看任务 · 点击项目看详情</span></div></section></>}
 <div className="daily-layout"><section className="daily-section" aria-label={view==='backlog'?'待处理任务':'每日任务清单'}><div className="daily-heading"><div><h2>{view==='backlog'?'重新安排':dayLabel(selected)}<span>{view==='backlog'?`${backlog.length} 项`:selected===today?'今天':['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][new Date(selected+'T12:00').getDay()]}</span></h2><p>{view==='backlog'?'保留原计划日期，不会自动顺延':`${dayProjectIds.size} 个项目 · ${daily.length} 项安排`}</p></div>{view==='timeline'?<div className="day-actions"><label className="jump-date"><CalendarDays size={16}/><span className="sr-only">跳转日期</span><input aria-label="跳转日期" type="date" min="1900-01-01" max="2100-12-31" value={selected} onInput={e=>chooseDay(e.currentTarget.value)}/></label><button className="btn" disabled={!canEdit} onClick={()=>newTask()}><Plus size={16}/> 添加任务</button></div>:<button className="btn" onClick={()=>chooseDay(today)}>回到今天</button>}</div>
 <div className="list-toolbar"><b>{view==='backlog'?'按原计划日期排列':'当天执行顺序'}</b><span>{view==='timeline'&&<><GripVertical size={13}/> 拖动或上下移动来排序</>}</span></div>
 <div className="task-list">{entries.map((e,index)=>{const task=taskMap.get(e.taskId)!,p=projectMap.get(task.projectId)!,siblings=data.entries.filter(x=>x.taskId===e.taskId),deadlineLate=!!task.deadline&&task.deadline<today&&siblings.some(x=>!x.done);return <article key={e.id} data-entry-id={e.id} className={`task-row ${e.done?'completed':''} ${dragId===e.id?'dragging':''}`} draggable={canEdit&&view==='timeline'} onDragStart={event=>{event.dataTransfer.setData('text/plain',e.id);event.dataTransfer.effectAllowed='move';setDragId(e.id)}} onDragEnd={()=>setDragId(null)} onDragOver={event=>{if(dragId&&view==='timeline')event.preventDefault()}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData('text/plain');if(dragId&&id===dragId)void reorder(id,e.id);setDragId(null)}}>
 <GripVertical className="drag-grip" size={16}/><Checkbox checked={e.done} disabled={!canEdit} aria-label={`${e.done?'取消完成':'完成'} ${e.title}`} onCheckedChange={v=>void toggle(e,!!v)}/><div className="task-body"><button className="task-title-button" disabled={!canEdit} onClick={()=>editEntry(e)}><h3>{e.title}</h3></button><div className="task-meta"><button className="project-tag" style={{color:p.color,background:p.color+'10'}} onClick={()=>setProjectId(p.id)}><i style={{background:p.color}}/>{p.name}</button>{siblings.length>1&&<span className="multiday-tag" title={task.title}>跨天 · {siblings.filter(x=>x.done).length}/{siblings.length} 天</span>}{view==='backlog'&&<span className="old-date">原计划 {dayLabel(e.date)}</span>}{deadlineLate&&<span className="overdue">已过截止日期</span>}</div>{(e.note||task.note)&&<p className="task-note" title={e.note||task.note}>{e.note||task.note}</p>}</div><span className="task-duration"><Clock3 size={13}/>{e.minutes?minutesLabel(e.minutes):'未估时'}</span><div className="row-controls">{view==='timeline'&&<div className="reorder-buttons"><button disabled={!canEdit||index===0} aria-label={`上移 ${e.title}`} onClick={()=>void reorder(e.id,entries[index-1].id)}><ArrowUp size={13}/></button><button disabled={!canEdit||index===entries.length-1} aria-label={`下移 ${e.title}`} onClick={()=>void reorder(e.id,entries[index+1].id)}><ArrowDown size={13}/></button></div>}<button className="row-open" disabled={!canEdit} onClick={()=>schedule(e)} aria-label={`改期 ${e.title}`} title="调整日期"><CalendarDays size={15}/></button><button className="row-open" disabled={!canEdit} onClick={()=>editEntry(e)} aria-label={`编辑 ${e.title}`} title="编辑任务与备注"><ArrowUpRight size={17}/></button></div></article>})}</div>
 {!entries.length&&<div className="empty-day"><Check size={28}/><h3>{view==='backlog'?'没有遗留的未完成事项':'这一天，还可以从容安排'}</h3><p>{view==='backlog'?'继续按自己的节奏推进。':'添加一件具体的事，让计划开始往前走。'}</p></div>}{view==='timeline'&&<button disabled={!canEdit} className="add-task-line" onClick={()=>newTask()}><Plus size={17}/> 为这一天添加一件事</button>}</section>
 <aside className="day-aside">{view==='timeline'&&<section className="day-summary"><div className="aside-heading"><h3>这一天的节奏</h3><Sparkles size={17}/></div><div className="hours-display">{Number((total/60).toFixed(1))}<span>小时</span></div><p>已填写的预计用时</p><div className="time-segments">{data.projects.filter(p=>dayProjectIds.has(p.id)).map(p=>{const n=daily.filter(e=>taskMap.get(e.taskId)?.projectId===p.id).reduce((s,e)=>s+(e.minutes||0),0);return n>0?<span key={p.id} style={{flex:n,background:p.color}}/>:null})}</div>{data.projects.filter(p=>dayProjectIds.has(p.id)).map(p=><div key={p.id} className="project-hours"><span><i style={{background:p.color}}/>{p.name}</span><b>{minutesLabel(daily.filter(e=>taskMap.get(e.taskId)?.projectId===p.id).reduce((s,e)=>s+(e.minutes||0),0))}</b></div>)}{unknown>0&&<div className="estimate-note"><CircleHelp size={15}/><span>还有 {unknown} 项任务未估时，实际投入可能更多。</span></div>}</section>}
 <section className="backlog-card"><div><span className="backlog-icon"><ListTodo size={17}/></span><b>{backlog.length?`还有 ${backlog.length} 项未完成`:'之前的安排都已处理'}</b></div><p>{backlog.length?<>之前的计划仍在这里，<br/>选个合适的时间继续。</>:'无需追赶，专注当下的工作。'}</p><button onClick={()=>setView(view==='backlog'?'timeline':'backlog')}>{view==='backlog'?'回到项目时间轴':'查看待处理事项'} <ArrowUpRight size={15}/></button></section><p className="aside-foot"><Check size={13}/> 每次推进，都算数。</p></aside></div>
 </div></main>
 {editor?.kind==='project'&&<ProjectEditor key={editor.project?.id||'new-project'} project={editor.project} date={selected} busy={busy} commit={commit} onClose={()=>setEditor(null)}/>}
 {editor?.kind==='task'&&<TaskEditor key={editor.task?.id||'new-task'} task={editor.task} entry={editor.entry} projectId={editor.projectId} date={selected} data={data} busy={busy} commit={commit} onClose={()=>setEditor(null)}/>}
 {editor?.kind==='move'&&<Dialog open onOpenChange={v=>{if(!v&&!busy)setEditor(null)}}><DialogContent className="editor-modal"><DialogTitle>重新安排日期</DialogTitle><DialogDescription>{editor.entry.title}</DialogDescription><form className="editor-form" onSubmit={async event=>{event.preventDefault();if(!validDate(moveDate)){toast.error('请选择有效日期');return;}const ok=await commit(s=>moveEntry(s,editor.entry.id,moveDate),'日期已调整');if(ok)setEditor(null);}}><p className="form-hint">原计划：{editor.entry.date}。改期后放到新日期清单末尾。</p><label>新的执行日期<input type="date" min="1900-01-01" max="2100-12-31" required value={moveDate} onInput={e=>setMoveDate(e.currentTarget.value)}/></label><div className="quick-dates"><button type="button" className="btn compact" onClick={()=>setMoveDate(today)}>今天</button><button type="button" className="btn compact" onClick={()=>setMoveDate(addDays(today,1))}>明天</button><button type="button" className="btn compact" onClick={()=>setMoveDate(addDays(today,7))}>一周后</button></div><div className="form-actions"><button type="button" className="btn" onClick={()=>setEditor(null)} disabled={busy}>取消</button><button className="btn primary" disabled={busy}>{busy?'保存中…':'保存日期'}</button></div></form></DialogContent></Dialog>}
 <Sheet open={!!visibleProject} onOpenChange={v=>{if(!v)setProjectId(null)}}><SheetContent className="project-sheet"><SheetHeader><SheetTitle><i style={{background:visibleProject?.color}}/>{visibleProject?.name}</SheetTitle><SheetDescription>{visibleProject?`${visibleProject.start} — ${visibleProject.end}`:''}</SheetDescription></SheetHeader>{visibleProject&&<div className="project-detail"><div className="project-detail-actions"><button className="btn" disabled={!canEdit} onClick={()=>{setProjectId(null);setEditor({kind:'project',project:visibleProject})}}><Pencil size={14}/> 编辑项目</button><button className="btn primary" disabled={!canEdit} onClick={()=>{setProjectId(null);newTask(visibleProject.id)}}><Plus size={14}/> 添加任务</button></div>{visibleProject.note&&<p className="project-description">{visibleProject.note}</p>}<h3>项目中的任务 <span>{data.tasks.filter(t=>t.projectId===visibleProject.id).length}</span></h3>{data.tasks.filter(t=>t.projectId===visibleProject.id).map(task=>{const rows=data.entries.filter(e=>e.taskId===task.id).sort((a,b)=>a.date.localeCompare(b.date)),n=rows.filter(e=>e.done).length;return <section className="project-task" key={task.id}><div><button className="project-task-title" disabled={!canEdit} onClick={()=>{setProjectId(null);setEditor({kind:'task',task})}}>{task.title}</button><button className="icon-button danger-hover" disabled={!canEdit} aria-label={`删除任务 ${task.title}`} onClick={()=>setRemove({kind:'task',id:task.id,name:task.title})}><Trash2 size={14}/></button></div><p>{n===rows.length?'已完成':`${n} / ${rows.length} 天已完成`}{task.deadline?` · 截止 ${task.deadline}`:''}</p><Progress aria-label={`${task.title}完成进度`} value={rows.length?n/rows.length*100:0}/>{rows.map(e=><button key={e.id} className="project-day" onClick={()=>{setProjectId(null);chooseDay(e.date)}}><span>{e.done?<Check size={13}/>:<span className="hollow-circle"/>}{dayLabel(e.date)}</span><b>{e.title}</b><ChevronRight size={13}/></button>)}</section>})}{!data.tasks.some(t=>t.projectId===visibleProject.id)&&<div className="empty-day"><CalendarDays size={28}/><p>项目已就绪，添加第一件具体的事。</p></div>}<button className="delete-project" disabled={!canEdit} onClick={()=>setRemove({kind:'project',id:visibleProject.id,name:visibleProject.name})}><Trash2 size={14}/> 删除项目</button></div>}</SheetContent></Sheet>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除{remove?.kind==='project'?'项目':'任务'}？</AlertDialogTitle><AlertDialogDescription>“{remove?.name}”及其全部每日记录将被删除，此操作无法恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} className="bg-destructive text-white hover:bg-destructive/90" onClick={event=>{event.preventDefault();void deleteConfirmed()}}>{busy?'正在删除…':'确认删除'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}
