'use client';
import { useState, type FormEvent } from 'react';
import { Plus, Trash2, CalendarDays } from 'lucide-react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { COLORS, addDays, type Planner, type Project, type Task, type Entry } from '@/lib/planner';
import { expandProjects, normalizeNewOrders, rangeDates } from '@/lib/planner-actions';
export type Commit=(change:(s:Planner)=>Planner,message?:string)=>Promise<boolean>;
const uid=()=>crypto.randomUUID();
export function ProjectEditor({project,date,busy,commit,onClose}:{project?:Project;date:string;busy:boolean;commit:Commit;onClose:()=>void}){
 const [draft,setDraft]=useState<Project>(project?{...project}:{id:uid(),name:'',color:COLORS[0],start:date,end:addDays(date,13),note:''});
 const change=(key:keyof Project,value:string)=>setDraft(current=>({...current,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();if(draft.end<draft.start){toast.error('结束日期不能早于开始日期');return;}
 const ok=await commit(s=>{if(project&&!s.projects.some(p=>p.id===project.id))throw new Error('这个项目已在其他设备删除，请关闭窗口后刷新。');const next={...s,projects:project?s.projects.map(p=>p.id===project.id?{...draft,name:draft.name.trim()}:p):[...s.projects,{...draft,name:draft.name.trim()}]};const expanded=expandProjects(next).projects.find(p=>p.id===draft.id)!;if(expanded.start!==draft.start||expanded.end!==draft.end)throw new Error('项目周期需要包含已有的任务日期，请先调整任务。');return next;},project?'项目已更新':'项目已创建');if(ok)onClose();}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="editor-modal"><DialogTitle>{project?'编辑项目':'新建项目'}</DialogTitle><DialogDescription>设置项目周期，开始安排每天的具体工作。</DialogDescription><form onSubmit={submit} className="editor-form"><label>项目名称<input autoFocus required maxLength={200} value={draft.name} onInput={e=>change('name',e.currentTarget.value)} placeholder="例如：品牌官网改版"/></label><div className="form-pair"><label>开始日期<input type="date" min="1900-01-01" max="2100-12-31" required value={draft.start} onInput={e=>change('start',e.currentTarget.value)}/></label><label>结束日期<input type="date" min={draft.start} max="2100-12-31" required value={draft.end} onInput={e=>change('end',e.currentTarget.value)}/></label></div><fieldset><legend>项目颜色</legend><div className="color-options">{COLORS.map((c,i)=><button type="button" key={c} aria-label={`颜色 ${['紫色','青色','橙色','粉色','蓝色','绿色'][i]}`} aria-pressed={draft.color===c} style={{background:c}} className={draft.color===c?'active':''} onClick={()=>change('color',c)}/>)}</div></fieldset><label>项目备注 <span>选填</span><textarea rows={3} maxLength={10000} value={draft.note} onInput={e=>change('note',e.currentTarget.value)} placeholder="项目目标或需要记住的事"/></label><div className="form-actions"><button type="button" className="btn" onClick={onClose} disabled={busy}>取消</button><button className="btn primary" disabled={busy}>{busy?'保存中…':project?'保存项目':'创建项目'}</button></div></form></DialogContent></Dialog>;
}
export function TaskEditor({task,entry,date,projectId,data,busy,commit,onClose}:{task?:Task;entry?:Entry;date:string;projectId?:string;data:Planner;busy:boolean;commit:Commit;onClose:()=>void}){
 const [draft,setDraft]=useState<Task>(task?{...task}:{id:uid(),projectId:projectId||data.projects[0]?.id||'',title:'',note:'',deadline:null});
 const [rows,setRows]=useState<Entry[]>(task?data.entries.filter(e=>e.taskId===task.id).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({...e})):[{id:uid(),taskId:'',date,title:'',note:'',minutes:null,done:false,order:0}]);
 const [end,setEnd]=useState(date),[weekdays,setWeekdays]=useState(false),[error,setError]=useState('');
 function changeRow(id:string,field:keyof Entry,value:string|boolean|number|null){setRows(current=>current.map(e=>e.id===id?{...e,[field]:value}:e));setError('');}
 function makeRange(){try{const days=rangeDates(rows[0].date,end).filter(d=>!weekdays||![0,6].includes(new Date(d+'T12:00:00').getDay()));if(!days.length)throw new Error('这个范围没有工作日，请调整日期。');setRows(days.map(date=>rows.find(r=>r.date===date)||{...rows[0],id:uid(),date,title:draft.title,note:'',done:false}));setError('');}catch(e){setError((e as Error).message)}}
 async function submit(e:FormEvent){e.preventDefault();if(!rows.length){setError('请至少安排一天');return;}if(new Set(rows.map(e=>e.date)).size!==rows.length){setError('同一任务在同一天只能有一条记录，请合并内容。');return;}
 const ok=await commit(s=>{if(task&&!s.tasks.some(t=>t.id===task.id))throw new Error('任务已在其他设备删除，请关闭窗口后刷新。');if(!s.projects.some(p=>p.id===draft.projectId))throw new Error('所属项目已不存在，请重新选择。');const validRows=normalizeNewOrders(s,rows.map(e=>({...e,taskId:draft.id,title:e.title.trim()||draft.title.trim()})));return expandProjects({...s,tasks:task?s.tasks.map(t=>t.id===task.id?{...draft,title:draft.title.trim()}:t):[...s.tasks,{...draft,title:draft.title.trim()}],entries:[...s.entries.filter(e=>e.taskId!==draft.id),...validRows]});},task?'任务与每日安排已保存':'任务已添加');if(ok)onClose();}
 const changed=entry?rows.find(e=>e.id===entry.id):null;
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="editor-modal task-editor"><DialogTitle>{task?'编辑任务与每日安排':'添加任务'}</DialogTitle><DialogDescription>{task?'修改每天的工作内容、备注或日期，所有视图会一起更新。':'单日任务安排一天；跨天任务可为每天填写不同内容。'}</DialogDescription><form onSubmit={submit} className="editor-form"><label>任务名称<input autoFocus required maxLength={200} value={draft.title} onInput={e=>{const title=e.currentTarget.value;setDraft(current=>({...current,title}))}} placeholder="例如：完成首页设计"/></label><div className="form-pair"><label>所属项目<Select value={draft.projectId} onValueChange={projectId=>setDraft(current=>({...current,projectId}))}><SelectTrigger aria-label="所属项目"><SelectValue/></SelectTrigger><SelectContent>{data.projects.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label><label>截止日期 <span>选填</span><input type="date" min="1900-01-01" max="2100-12-31" value={draft.deadline||''} onInput={e=>{const deadline=e.currentTarget.value||null;setDraft(current=>({...current,deadline}))}}/></label></div><label>任务备注 <span>所有日期共用</span><textarea rows={2} maxLength={10000} value={draft.note} onInput={e=>{const note=e.currentTarget.value;setDraft(current=>({...current,note}))}} placeholder="任务整体要求、参考信息等"/></label>
 <div className="schedule-section"><h3><CalendarDays size={16}/> 每日安排 <span>{rows.length} 天 · {rows.filter(r=>r.done).length} 天已完成</span></h3>{!task&&<div className="range-builder"><label>安排到<input type="date" min={rows[0]?.date||date} max="2100-12-31" value={end} onInput={e=>setEnd(e.currentTarget.value)}/></label><label className="inline-check"><Checkbox checked={weekdays} onCheckedChange={v=>setWeekdays(!!v)}/>跳过周末</label><button className="btn compact" type="button" onClick={makeRange}>生成每日记录</button></div>}
 {rows.map((r,i)=><div className={`schedule-row ${r.id===changed?.id?'focused-day':''}`} key={r.id}><div className="schedule-row-head"><label className="sr-only" htmlFor={`date-${r.id}`}>第 {i+1} 天日期</label><input id={`date-${r.id}`} aria-label={`第 ${i+1} 天日期`} type="date" min="1900-01-01" max="2100-12-31" required value={r.date} onInput={e=>changeRow(r.id,'date',e.currentTarget.value)}/><label className="inline-check"><Checkbox checked={r.done} onCheckedChange={v=>changeRow(r.id,'done',!!v)}/>当天完成</label><button type="button" className="icon-button danger-hover" disabled={rows.length===1||busy} aria-label={`移除第 ${i+1} 天安排`} onClick={()=>setRows(rows.filter(e=>e.id!==r.id))}><Trash2 size={15}/></button></div><div className="form-pair task-row-fields"><label>当天工作<input maxLength={200} value={r.title} onInput={e=>changeRow(r.id,'title',e.currentTarget.value)} placeholder={draft.title||'当天具体要做什么'}/></label><label>预计分钟<input type="number" min={1} max={1440} value={r.minutes??''} onInput={e=>changeRow(r.id,'minutes',e.currentTarget.value===''?null:Number(e.currentTarget.value))} placeholder="选填"/></label></div><label>当天备注<textarea rows={2} maxLength={10000} value={r.note} onInput={e=>changeRow(r.id,'note',e.currentTarget.value)} placeholder="这一天需要留意的事"/></label></div>)}<button type="button" className="add-task-line" onClick={()=>setRows([...rows,{id:uid(),taskId:draft.id,date:addDays(rows.at(-1)?.date||date,1),title:'',note:'',minutes:null,done:false,order:0}])}><Plus size={15}/> 再安排一天</button><p className="form-hint">所有每日记录完成后，整项任务自动完成。超出项目周期的安排会自动扩展项目日期。</p></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>取消</button><button className="btn primary" disabled={busy}>{busy?'保存中…':'保存任务'}</button></div></form></DialogContent></Dialog>;
}
